### ISSUE TITLE
Monospace font for code/pre on the site

### ISSUE THREAD

**Issue by jcubic** [htty/htty#130]
On the site there should be `monospace` font-family as the last one. On my machine I've got serif text instead of monospace (Xubuntu).
![przechwycenie obrazu ekranu_2015-09-14_16-35-02](https://cloud.githubusercontent.com/assets/280241/9852471/a961a41a-5afe-11e5-94aa-69ce14bd986c.png)

**Comment by njonsson** [comment]
Fixed in https://github.com/htty/htty/commit/0c32978ba45771b26a31754810c208f663596db7. Hopefully I won’t forget to reapply this next time I regenerate using GitHub Pages.
