### ISSUE TITLE
Accessible examples

### ISSUE THREAD

**Issue by JosielSantos** [htty/htty#134]
Hello.

The project seems to be interesting, but can you past the examples in the readme as plain text? I am totally blind and can not see the images.

Thanks.

**Comment by njonsson** [comment]
Thank you for bringing this to my attention. I will create an examples file that mirrors the images but in Markdown.

**Comment by njonsson** [comment]
Added in 96870b8101e21bdff44d9571c0eaf8f32606ca25: [examples.markdown](https://github.com/htty/htty/blob/master/examples.markdown).

**Comment by JosielSantos** [comment]
Thanks for the attention and the great job!
