### ISSUE TITLE
Report response times

### ISSUE THREAD

**Issue by rjackson90** [htty/htty#140]
I really like using Htty so far, but it would be **really** nice to have an indication of how long it took to get a response from the server. Similar to the "time to first byte" number reported by Chrome's developer tools. I use Htty to debug API endpoints for my web applications, and performance is a critical feature.

**Comment by presskey** [comment]
@rjackson90 @njonsson I've created pull request for this. Please check if that's what you need.

**Comment by njonsson** [comment]
Addressed in 693137bfe1ab63889ef936f6cd9cea67c801aab3.
