### ISSUE TITLE
Uninitialized constant HTTY::CLI::HTTPMethodCommand::OpenSSL on a fresh install

### ISSUE THREAD

**Issue by shulard** [htty/htty#146]
Hello,

I discovered your tool today and decide to give it a try :smile:

I just wrote on my mac :
```shell
sudo gem install htty
```

I use the default ruby version bundled with Mac OS (2.0.0p645) and the installation process just ended fine.

Then I try to use it on my website :

```
htty http://www.chstudio.fr
```

The tool start and when I request a `get` call I receive the following error :
```
*** Uninitialized constant HTTY::CLI::HTTPMethodCommand::OpenSSL
```

I'm not a ruby master but it's seem to be a missing configuration ?

**Comment by AleksanderGrzybowski** [comment]
Same here, ruby 2.1.5p273, htty-1.5.5.gem, I recall playing with this tool a few months ago and there were no problems then.

**Comment by njonsson** [comment]
Good catch! This is fixed in:

* e93e738b53fc6cc72136c3c97871676bdf35818c
* 7b8244e7c7dca0f05c46fca9bcdb1d4e3639ec21 (v1._x_ branch)
* [v1.5.6](https://rubygems.org/gems/htty/versions/1.5.6)

**Comment by shulard** [comment]
Hello,

Thanks for the update, I've just retrieved the new gem but there is another error. Maybe I don't use the tool the right way.

```
http://chstudio.fr/> get
*** /Library/Ruby/Gems/2.0.0/gems/htty-1.5.6/lib/htty/requests_util.rb:107: syntax error, unexpected =>, expecting keyword_end
                                      :time    => response_time)
                                                 ^
/Library/Ruby/Gems/2.0.0/gems/htty-1.5.6/lib/htty/requests_util.rb:123: dynamic constant assignment
/Library/Ruby/Gems/2.0.0/gems/htty-1.5.6/lib/htty/requests_util.rb:126: syntax error, unexpected end-of-input, expecting keyword_end
```

**Comment by njonsson** [comment]
Another good catch. I’ve yanked that gem release and replaced it with [v1.5.7](https://rubygems.org/gems/htty/versions/1.5.7).
